### PR TITLE
Webui survey integration

### PR DESCRIPTION
**Pull request by dstreet26**
# Description

This branch was created to merge the [survey prototype code](https://github.com/kindlyops/elm-survey-prototype) into the main mappamundi web app. This is the quick feature list:

- Ipsative Surveys
- Likert Surveys
- Elm Code re-organization
- Migrations for Survey Schemas and Views
- Daemonite Material instead of Material Components Web
- Improved Sidebar Navigation
- Survey Responses
- Extra Surveys to Demo/Test with

## Surveys

There are 2 types of surveys: Ipsative and Likert

Both surveys have a list of Questions and the same kind of Metadata.

### Ipsative

Ipsative Questions have point-based responses for each group in each answer, and a maximum amount of points to spend per group.

Ipsative Responses consist of the answer id, group number, and points assigned to that group.

### Likert

Likert Questions have a matrix of answers and choices. Only one choice per answer can be selected.

Likert Responses consist of the answer id and the choice that was made in text form.

## CSS Framework

The Elm Survey Prototype was first built with [elm-style-elements](https://github.com/mdgriffith/style-elements/), but then moved to Bootstrap 4. The mappamundi webui was built with SCSS and Material Components web (MDC). MDC was lacking many components like a sidenav.

In order to get the best of both MDC and Bootstrap, I decided to use [daemonite-material](https://github.com/Daemonite/material)

Currently, this is variabalized with a `custom.scss` file and needs to be manually built (with `npm run build_css`). I want to have this step automated before merging this branch.

## Schema

The following things can be ordered by using an `order_number`:

- Questions in a Survey
- Answers in a Question
- Choices in a Likert Question

Choices in a Likert Survey can be different on a question-by-question basis. Each Likert Question points to a "Choice Group" which itself is a list of choices. So the first question in a Likert Survey can have choices like "Strongly Disagree, Disagree, Neutral, Agree, Strongly Agree", and the next question can have a different set of choices (like only "Disagree, Agree" or "Male, Female").

## Still to do before merge

Fix the way the CSS is built. --done

## What to do after this

Load a survey given a url with a uuid in it. Figure out what this means to a non-logged in user.

### CODE REVIEW

**Comment by statik** [comment]
I am SOOO excited for this!

One thing I saw on a failing CircleCI test was a failure in the DB migrations, the error was "ERROR: Wrong migration name format: V12_likert_demo.sql(It should look like this: V1.2__Description.sql)". I guess flyway is picky about having those double underscores 🤷‍♂️ 

Will continue looking more as I get time.

**Comment by dstreet26** [comment]
While on the topic of migrations, should I condense the 10 of them down to 3 or 4?

**Comment by statik** [comment]
If collapsing the migrations is helpful for you, sure! Not needed from my
side though.
-- 
Elliot Murphy | Kindly Ops <https://www.kindlyops.com> is *DevOps for
regulated industries*
Secure CI/CD, Independent Security Assessments, AWS & GCP

**Comment by dstreet26** [comment]
I'll leave them separate, I think they add documentation value and cost nothing performance-wise.

I want to clean up those TODO's before merging. Yay for Codeclimate because I had completely forgotten about them.

**Pull request merged**
