### PR TITLE
All new dashboard with Material Design

### PR DESCRIPTION
**Pull request by laurencaitlan**
Major redesign of Main.elm with MD.
Signed-off-by: Lauren Behan <lauren.caitlan@gmail.com>

TODO: 
- Finish up the Regulations model to rid it of Paper elements. 👍 
- Delete the remaining WebComponents no longer being used. 👍 
- Figure out the constantly frustrating height issues and why it's shortening the drawer when changing from desktop -> mobile 
- Landscape on mobile drawer scroll and overflow scroll in general. Something isn't right.

### CODE REVIEW

**Comment by laurencaitlan** [comment]
This compiles but won't work as intended. When I add `Ports.applyMDC` to Cmd.batch list on line 27 the compiler says all the entries need the same type. In the process of learning and figuring out union types and if that will help.

**Comment by joelclermont** [comment]
I hope you don't mind the unsolicited comment, but I'm still subscribed to the repo and I love watching the progress. Mapping each JS interaction as a pair of ports is a bit of an anti-pattern. A nicer approach is to have one pair of ports for your whole application.

This concept was summarized really nicely by Murphy Randle at elm-conf last month. The video of his talk is posted and I highly recommend it! https://www.youtube.com/watch?v=P3pL85n9_5s

If you have any follow up questions, I'll do my best to help.

**Comment by statik** [comment]
@joelclermont thank you! Your insights are always welcome. Amazing timing, I had actually watched that video and went back and listened to the Elm Town podcast episode on Sunday, and have a TODO to implement that pattern to coalesce the ports as advised in that talk. I had purchased a ticket to ElmConf earlier in the year and am really sad I had to return it when I wasn't able to attend.

The big issue we are trying to overcome here is timing the call to `window.mdc.autoInit();` to line up appropriately with when Elm adds nodes to the DOM, since we want the MDC library to animate the text fields. It seems that this use case has been accepted as a new feature for elm, #19 on the list at elm-lang/html#53. Since that isn't available yet, an alternative I just worked out is to use Arrive.js to watch for element creation (using the MutationObserver API). This seems preferable to the other hacks I've seen like https://github.com/fredcy/elm-defer-command.

**Comment by joelclermont** [comment]
@statik very interesting approach and seems like it fits your use case well. If you make it to next year's elm-conf, we'll definitely have to meet up. elm-conf and StrangeLoop is already blocked on my calendar for 2018 😄

**Comment by statik** [comment]
@laurencaitlan I think this is working pretty smoothly now! I also adjusted the autoInit call to suppress the warnings about already initialized components because we get triggered once for every text field that is added, but I think thats reasonable per the MDC autoInit docs we were looking at today.

**Comment by laurencaitlan** [comment]
@joelclermont @statik Thank you both for the help! I can always use it, and especially with learning elm :)

**Pull request merged**
